### ISSUE TITLE
decoding of latex strings

### ISSUE THREAD

**Issue by pseyfert** [KonstantinSchubert/eventtype#1]
With event type 11296012, I see the row

> 9 cc- meson: $geq$ 0, open-charm hadron: $geq$ 2, muon: 0 , electron : 0

which is human readable enough, but for bonus points the `$geq$` should be converted into a proper greater-or-equal symbol

**Comment by KonstantinSchubert** [comment]
yes, I am planning on adding Katex today.

**Comment by KonstantinSchubert** [comment]
in fact, maybe "at least" does a better job than $geq$ ?

**Comment by pseyfert** [comment]
seems better, indeed. I'm just wondering about the

> $geq$ 0

which would strange in both ways, with the $\geq$ and as "at least 0".

**Comment by KonstantinSchubert** [comment]
Yea, in fact by leaving it out the message is the same. Btw, I have the latex engine going now, but most of the strings still need to be updated.
