### ISSUE TITLE
Some templates are still missing

### ISSUE THREAD

**Issue by KonstantinSchubert** [KonstantinSchubert/eventtype#2]
The missing templates are:

builder/get_gas_type.html
builder/get_eta_range.html
builder/get_four_momentum.html

**Comment by pseyfert** [comment]
is [that, and what follows when checking J/ψ→µµ,](http://eventtype.boosted.science/build/?c_flag=4&s_flag=9&g_flag=5) covered by this issue?

**Comment by KonstantinSchubert** [comment]
nope, thanks....

**Comment by KonstantinSchubert** [comment]
working on it now

**Comment by KonstantinSchubert** [comment]
should be fixed, except for the fact thtat there is only a single option to choose from.
