### ISSUE TITLE
Wrong description of the 6th digit

### ISSUE THREAD

**Issue by Kecksdose** [KonstantinSchubert/eventtype#4]
It says

```
Select one or more of the following
```

but it also possible (and sometimes necessary) to choose none of them.

**Comment by KonstantinSchubert** [comment]
I changed it to "Select what applies to the decay" .

I hope that's okay, I am open for suggestions.

**Comment by KonstantinSchubert** [comment]
I tried to clarify it even more, I guess it is okay now.
