### ISSUE TITLE
eventtype search helper

### ISSUE THREAD

**Issue by pseyfert** [KonstantinSchubert/eventtype#6]
i was just wondering if i can (ab/re)use the event type builder to tell me where in the bookkeeping to look for "interesting" event types.

as in "I look for some neutral B, decaying to open charm, but no leptons, i actually don't care if cocktail or fully forced decays… give the the pattern of event types to look for".

the main addition that the event type builder would need is a "skip question" button, so one has a few more "X" in the final event type.

**Comment by KonstantinSchubert** [comment]
The point is that the flags are not orthogonal, their meaning often depends on the other flags. If the e.g. the first flag is skipped, none of the other flags can be determined. At last this means that skipping a flag will make you reach the end of the wizard pretty fast...

I'm not saying it can be implemented, but I have to see how to include it into the current logic. You can have a look at the current implementation here: https://github.com/KonstantinSchubert/eventtype/blob/master/eventtype/resolver/views.py#L59 (needs some refactoring)

**Comment by pseyfert** [comment]
hm, right skipping the "forced decay" seems easy but as you say the first question seems impossible…
