### ISSUE TITLE
NameError when the general flag is set to 6

### ISSUE THREAD

**Issue by chrisburr** [KonstantinSchubert/eventtype#7]
Example URL: http://eventtype.boosted.science/resolve/?event_number_input=60001001

**Comment by KonstantinSchubert** [comment]
Thanks. It should be working a bit better now, but there is an empty entry which I am working to fix.

**Comment by KonstantinSchubert** [comment]
I am still debugging right now, things might break a bit during the next hour.

**Comment by KonstantinSchubert** [comment]
Alright, should be fine now. Thanks for pointing out the issue!

**Comment by chrisburr** [comment]
Thanks for the prompt fix! :+1:
