### ISSUE TITLE
Add a licence

### ISSUE THREAD

**Issue by admorris** [KonstantinSchubert/eventtype#8]
Hi @KonstantinSchubert. There is some interest on the `lhcb-simulation` list in cloning this to the CERN GitLab and making it an official LHCb project. As the author, are you OK with this? I suggest adding a licence to the repo either way. The CB plans to adopt GPLv3 for all LHCb software soon, so that would be most suitable.

**Comment by chrisburr** [comment]
@KonstantinSchubert As this comes up quite often, are you happy for someone to fork this under the standard LHCb licence:
```
###############################################################################
# (c) Copyright 2000-2019 CERN for the benefit of the LHCb Collaboration      #
#                                                                             #
# This software is distributed under the terms of the GNU General Public      #
# Licence version 3 (GPL Version 3), copied verbatim in the file "COPYING".   #
#                                                                             #
# In applying this licence, CERN does not waive the privileges and immunities #
# granted to it by virtue of its status as an Intergovernmental Organization  #
# or submit itself to any jurisdiction.                                       #
###############################################################################
```
where [`COPYING` can be found here](https://gitlab.cern.ch/lhcb/DaVinci/blob/master/COPYING)?

Or another licence and copyright statement of your choosing?

**Comment by KonstantinSchubert** [comment]
Hi @chrisburr 

I am happy with that licence.

Can you create a PR for adding the license and adding the COPYING file? Then I will merge it. 

Once you created the issue, send me a quick reminder to check at mail@konstantinschubert.com
